// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimingDemo.Api.Data;

#nullable disable

namespace TimingDemo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926191701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimingDemo.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("TimingDemo.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 999.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "C# in Depth",
                            Price = 45.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Name = "T-Shirt",
                            Price = 15.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Smartphone",
                            Price = 599.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Clean Code",
                            Price = 40.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Jeans",
                            Price = 35.50m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Headphones",
                            Price = 199.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Design Patterns",
                            Price = 55.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Jacket",
                            Price = 89.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Name = "Monitor",
                            Price = 299.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Domain-Driven Design",
                            Price = 50.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Sneakers",
                            Price = 75.00m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Name = "Keyboard",
                            Price = 120.00m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Refactoring",
                            Price = 48.00m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Socks",
                            Price = 9.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Name = "Mouse",
                            Price = 49.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Name = "Clean Architecture",
                            Price = 42.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Name = "Sweater",
                            Price = 45.00m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Name = "Tablet",
                            Price = 499.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Name = "Pragmatic Programmer",
                            Price = 39.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Name = "Hat",
                            Price = 19.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Name = "Smartwatch",
                            Price = 250.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Name = "CLR via C#",
                            Price = 55.00m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Name = "Scarf",
                            Price = 25.00m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Name = "Webcam",
                            Price = 79.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Name = "Pro ASP.NET Core",
                            Price = 60.00m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Name = "Gloves",
                            Price = 14.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            Name = "Microphone",
                            Price = 150.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Name = "Code Complete",
                            Price = 65.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Name = "Shorts",
                            Price = 29.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Name = "Speakers",
                            Price = 199.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Name = "Effective C#",
                            Price = 45.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Name = "Belt",
                            Price = 34.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            Name = "Router",
                            Price = 129.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Name = "Dependency Injection",
                            Price = 50.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Name = "Suit",
                            Price = 199.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Name = "External HDD",
                            Price = 89.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Name = "Soft Skills",
                            Price = 25.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            Name = "Tie",
                            Price = 15.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            Name = "USB Hub",
                            Price = 29.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            Name = "Mythical Man-Month",
                            Price = 35.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Name = "Boots",
                            Price = 120.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 1,
                            Name = "Power Bank",
                            Price = 49.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            Name = "Patterns of Enterprise Architecture",
                            Price = 55.00m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            Name = "Sandals",
                            Price = 39.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 1,
                            Name = "Earbuds",
                            Price = 149.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            Name = "Working Effectively with Legacy Code",
                            Price = 48.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 3,
                            Name = "Tracksuit",
                            Price = 65.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            Name = "Graphics Card",
                            Price = 699.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            Name = "Building Microservices",
                            Price = 50.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 3,
                            Name = "Beanie",
                            Price = 12.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 1,
                            Name = "Motherboard",
                            Price = 199.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            Name = "Designing Data-Intensive Applications",
                            Price = 45.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 3,
                            Name = "Polo Shirt",
                            Price = 25.00m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 1,
                            Name = "CPU",
                            Price = 299.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 2,
                            Name = "Head First Design Patterns",
                            Price = 40.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 3,
                            Name = "Vest",
                            Price = 45.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 1,
                            Name = "RAM 16GB",
                            Price = 75.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 2,
                            Name = "Release It!",
                            Price = 38.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 3,
                            Name = "Cardigan",
                            Price = 55.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 1,
                            Name = "SSD 1TB",
                            Price = 110.00m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 2,
                            Name = "Continuous Delivery",
                            Price = 42.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 3,
                            Name = "Blazer",
                            Price = 150.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 1,
                            Name = "Gaming Chair",
                            Price = 250.00m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 2,
                            Name = "Test Driven Development",
                            Price = 35.00m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 3,
                            Name = "Trench Coat",
                            Price = 199.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 1,
                            Name = "Mechanical Keyboard",
                            Price = 130.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            Name = "The Phoenix Project",
                            Price = 25.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 3,
                            Name = "Swimsuit",
                            Price = 45.00m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 1,
                            Name = "Wireless Mouse",
                            Price = 55.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 2,
                            Name = "Grokking Algorithms",
                            Price = 39.99m,
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 3,
                            Name = "Overalls",
                            Price = 59.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 1,
                            Name = "Cooling Pad",
                            Price = 25.00m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 2,
                            Name = "C# 10 and .NET 6",
                            Price = 55.00m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 3,
                            Name = "Pajamas",
                            Price = 35.00m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 1,
                            Name = "USB Flash Drive",
                            Price = 15.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 2,
                            Name = "Programming Pearls",
                            Price = 32.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 3,
                            Name = "Raincoat",
                            Price = 85.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 1,
                            Name = "Docking Station",
                            Price = 199.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 2,
                            Name = "Code: The Hidden Language",
                            Price = 28.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 3,
                            Name = "Sunglasses",
                            Price = 120.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 1,
                            Name = "Ethernet Cable",
                            Price = 10.00m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 2,
                            Name = "Structure and Interpretation",
                            Price = 60.00m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 3,
                            Name = "Watch",
                            Price = 299.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 1,
                            Name = "HDMI Cable",
                            Price = 15.00m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 2,
                            Name = "Cracking the Coding Interview",
                            Price = 35.00m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 3,
                            Name = "Wallet",
                            Price = 45.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 1,
                            Name = "VR Headset",
                            Price = 399.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 2,
                            Name = "Site Reliability Engineering",
                            Price = 45.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 3,
                            Name = "Backpack",
                            Price = 65.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 1,
                            Name = "Drone",
                            Price = 799.99m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 2,
                            Name = "The Pragmatic Programmer",
                            Price = 42.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 3,
                            Name = "Mittens",
                            Price = 18.00m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 1,
                            Name = "Camera",
                            Price = 599.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 2,
                            Name = "Clean Agile",
                            Price = 38.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 3,
                            Name = "Polo",
                            Price = 30.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 1,
                            Name = "Tripod",
                            Price = 45.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 2,
                            Name = "Peopleware",
                            Price = 35.00m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 3,
                            Name = "Flip Flops",
                            Price = 15.00m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 1,
                            Name = "MicroSD Card",
                            Price = 25.00m,
                            StockQuantity = 110
                        });
                });

            modelBuilder.Entity("TimingDemo.Api.Models.Product", b =>
                {
                    b.HasOne("TimingDemo.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TimingDemo.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
